import { join, dirname, basename, relative, extname } from "node:path";
import { readdirSync, statSync, existsSync, readFileSync } from "node:fs";
import type { MemoryDatabase } from "../store/database.js";
import type { RepoMemoryConfig } from "../config/config.js";
import type { DetectedConventions } from "../indexer/conventions.js";
import type { DependencyGraph } from "../indexer/dependency-resolver.js";
import type { ScannedFile } from "../indexer/scanner.js";
import { getLanguageStats } from "../indexer/scanner.js";
import { estimateTokens, truncateToTokens } from "../utils/tokens.js";
import { getCurrentCommitHash, getRemoteUrl } from "../utils/git.js";

interface GeneratorContext {
  db: MemoryDatabase;
  config: RepoMemoryConfig;
  conventions: DetectedConventions;
  depGraph: DependencyGraph;
  files: ScannedFile[];
  rootDir: string;
}

/**
 * Generate the MEMORY.md file from the indexed data.
 */
export function generateMemoryFile(ctx: GeneratorContext): string {
  const sections: string[] = [];
  const timestamp = new Date().toISOString().replace(/\.\d+Z$/, "Z");
  const stats = ctx.db.getStats();
  const repoName = basename(ctx.rootDir);
  const commitHash = getCurrentCommitHash(ctx.rootDir);
  const langStats = getLanguageStats(ctx.files);
  const primaryLang = langStats[0]?.language || "unknown";

  // ─── Header ───
  sections.push(`# 🧠 Repository Memory

> Auto-generated by [repo-memory](https://github.com/aakashpawar1999/repo-memory). Do not edit manually.
> Last indexed: ${timestamp}${commitHash ? ` | Commit: ${commitHash}` : ""}
> **${repoName}** | ${stats.files} files | ${stats.symbols} symbols | Primary: ${capitalize(primaryLang)}`);

  // ─── Project Overview ───
  sections.push(generateProjectOverview(ctx));

  // ─── Architecture Map ───
  sections.push(generateArchitectureMap(ctx));

  // ─── Key Files & Symbols ───
  sections.push(generateKeySymbols(ctx));

  // ─── Dependency Graph ───
  if (ctx.config.includeDependencies) {
    sections.push(generateDependencySection(ctx));
  }

  // ─── Conventions ───
  if (ctx.config.includeConventions) {
    sections.push(generateConventionsSection(ctx));
  }

  // ─── Critical Paths ───
  sections.push(generateCriticalPaths(ctx));

  let output = sections.filter(Boolean).join("\n\n---\n\n");

  // Token-aware truncation
  const tokens = estimateTokens(output);
  if (tokens > ctx.config.maxTokens) {
    output = truncateToTokens(output, ctx.config.maxTokens);
  }

  return output;
}

/**
 * Get estimated token count of the generated output.
 */
export function getMemoryTokenCount(content: string): number {
  return estimateTokens(content);
}

// ─── Section Generators ─────────────────────────────────────────────

function generateProjectOverview(ctx: GeneratorContext): string {
  const conv = ctx.conventions;
  const langStats = getLanguageStats(ctx.files);

  const lines: string[] = ["## 📋 Project Overview"];

  if (conv.projectType) {
    lines.push(`- **Type**: ${conv.projectType} application`);
  }

  if (langStats.length > 0) {
    const langLine = langStats
      .slice(0, 4)
      .map((l) => `${capitalize(l.language)} (${l.percentage}%)`)
      .join(", ");
    lines.push(`- **Languages**: ${langLine}`);
  }

  if (conv.packageManager)
    lines.push(`- **Package Manager**: ${conv.packageManager}`);
  if (conv.buildTool) lines.push(`- **Build Tool**: ${conv.buildTool}`);
  if (conv.testFramework)
    lines.push(`- **Test Framework**: ${conv.testFramework}`);
  if (conv.linter) lines.push(`- **Linter**: ${conv.linter}`);
  if (conv.formatter) lines.push(`- **Formatter**: ${conv.formatter}`);

  if (conv.entryPoints.length > 0) {
    lines.push(
      `- **Entry Points**: ${conv.entryPoints.map((e) => "`" + e + "`").join(", ")}`,
    );
  }

  if (conv.buildCommand) lines.push(`- **Build**: \`${conv.buildCommand}\``);
  if (conv.testCommand) lines.push(`- **Test**: \`${conv.testCommand}\``);
  if (conv.devCommand) lines.push(`- **Dev**: \`${conv.devCommand}\``);

  return lines.join("\n");
}

function generateArchitectureMap(ctx: GeneratorContext): string {
  const lines: string[] = ["## 🏗️ Architecture Map", "", "```"];

  // Build a tree structure
  const tree = buildDirectoryTree(ctx.files, ctx.config.maxTreeDepth);
  const treeLines = renderTree(tree, "", true);
  lines.push(...treeLines);

  lines.push("```");
  return lines.join("\n");
}

function generateKeySymbols(ctx: GeneratorContext): string {
  const lines: string[] = ["## 🗂️ Key Files & Symbols"];

  const allSymbols = ctx.db.getAllSymbols();
  const fanIn = ctx.db.getFanInCounts();

  // Group symbols by file
  const fileSymbols = new Map<string, typeof allSymbols>();
  for (const sym of allSymbols) {
    const path = sym.file_path;
    if (!fileSymbols.has(path)) fileSymbols.set(path, []);
    fileSymbols.get(path)!.push(sym);
  }

  // Score and rank files by importance
  const fileScores: Array<{
    path: string;
    score: number;
    symbols: typeof allSymbols;
    fanInCount: number;
  }> = [];

  for (const [path, symbols] of fileSymbols) {
    const fanInCount = fanIn.get(path) || 0;
    const exportedCount = symbols.filter((s) => s.exported).length;
    const classCount = symbols.filter((s) => s.kind === "class").length;
    const score =
      fanInCount * 3 + exportedCount * 2 + classCount * 2 + symbols.length;
    fileScores.push({ path, score, symbols, fanInCount });
  }

  fileScores.sort((a, b) => b.score - a.score);

  const maxFiles = Math.min(ctx.config.maxKeySymbols, fileScores.length);
  let symbolCount = 0;

  for (let i = 0; i < maxFiles && symbolCount < ctx.config.maxKeySymbols; i++) {
    const { path, symbols, fanInCount } = fileScores[i];

    if (symbols.length === 0) continue;

    const allFiles = ctx.db.getAllFiles();
    const file = allFiles.find((f) => f.path === path);
    const lineRange = file ? ` (L1-L${file.lineCount})` : "";
    const depNote = fanInCount > 0 ? ` — ${fanInCount} dependents` : "";

    lines.push("");
    lines.push(`### \`${path}\`${lineRange}${depNote}`);

    // List symbols
    for (const sym of symbols) {
      if (symbolCount >= ctx.config.maxKeySymbols) break;

      const lineInfo = ctx.config.includeLineNumbers
        ? ` (L${sym.startLine}-L${sym.endLine})`
        : "";

      const icon = getSymbolIcon(sym.kind);
      const exportBadge = sym.exported ? " `exported`" : "";

      if (ctx.config.includeSignatures && sym.signature) {
        lines.push(
          `- ${icon} **\`${sym.qualifiedName}\`**${lineInfo}${exportBadge}`,
        );
        if (sym.kind !== "constant" && sym.kind !== "type") {
          lines.push(`  - \`${cleanSignature(sym.signature)}\``);
        }
      } else {
        lines.push(
          `- ${icon} **\`${sym.qualifiedName}\`** (${sym.kind})${lineInfo}${exportBadge}`,
        );
      }

      if (sym.docstring) {
        const doc =
          sym.docstring.length > 100
            ? sym.docstring.slice(0, 100) + "..."
            : sym.docstring;
        lines.push(`  - ${doc}`);
      }

      symbolCount++;
    }
  }

  return lines.join("\n");
}

function generateDependencySection(ctx: GeneratorContext): string {
  const lines: string[] = ["## 🔗 Dependency Graph"];

  // Top depended-on files
  const fanIn = ctx.db.getFanInCounts();
  const topDeps = Array.from(fanIn.entries())
    .sort((a, b) => b[1] - a[1])
    .slice(0, 15);

  if (topDeps.length > 0) {
    lines.push("");
    lines.push("### Most Depended-On Files (Fan-In)");
    lines.push("| File | Dependents | Impact |");
    lines.push("|------|-----------|--------|");

    for (const [path, count] of topDeps) {
      const impact =
        count >= 10 ? "🔴 Critical" : count >= 5 ? "🟡 High" : "🟢 Normal";
      lines.push(`| \`${path}\` | ${count} | ${impact} |`);
    }
  }

  // Circular dependencies
  if (ctx.depGraph.circularDeps.length > 0) {
    lines.push("");
    lines.push("### ⚠️ Circular Dependencies");
    for (const [a, b] of ctx.depGraph.circularDeps.slice(0, 10)) {
      lines.push(`- \`${a}\` ↔ \`${b}\``);
    }
  }

  // External packages
  const topPackages = Array.from(ctx.depGraph.externalPackages.entries())
    .sort((a, b) => b[1] - a[1])
    .slice(0, 15);

  if (topPackages.length > 0) {
    lines.push("");
    lines.push("### 📦 External Dependencies (by usage)");
    for (const [pkg, count] of topPackages) {
      lines.push(`- \`${pkg}\` — used in ${count} files`);
    }
  }

  return lines.join("\n");
}

function generateConventionsSection(ctx: GeneratorContext): string {
  const conv = ctx.conventions;
  const lines: string[] = ["## 📐 Conventions & Patterns"];

  lines.push(`- **File Naming**: ${conv.fileNaming}`);
  lines.push(`- **Function Naming**: ${conv.functionNaming}`);

  if (conv.testPattern) {
    lines.push(
      `- **Testing**: ${conv.testFramework || "Unknown"}, ${conv.testPattern}`,
    );
  }

  if (conv.projectType) {
    lines.push(`- **Framework**: ${conv.projectType}`);
  }

  if (conv.linter) lines.push(`- **Linting**: ${conv.linter}`);
  if (conv.formatter) lines.push(`- **Formatting**: ${conv.formatter}`);

  return lines.join("\n");
}

function generateCriticalPaths(ctx: GeneratorContext): string {
  const lines: string[] = ["## 🚨 Critical Paths"];
  lines.push("");
  lines.push(
    "Files with highest impact — changes here cascade across the codebase:",
  );
  lines.push("");

  const fanIn = ctx.db.getFanInCounts();
  const criticalFiles = Array.from(fanIn.entries())
    .filter(([, count]) => count >= 3)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 10);

  if (criticalFiles.length === 0) {
    lines.push(
      "_No critical dependency hotspots detected (all files have < 3 dependents)._",
    );
    return lines.join("\n");
  }

  for (let i = 0; i < criticalFiles.length; i++) {
    const [path, count] = criticalFiles[i];
    const allSymbols = ctx.db.getAllSymbols();
    const fileSymbols = allSymbols.filter((s) => s.file_path === path);
    const exportedNames = fileSymbols
      .filter((s) => s.exported)
      .map((s) => s.name)
      .slice(0, 5);

    lines.push(
      `${i + 1}. **\`${path}\`** — ${count} dependents${
        exportedNames.length > 0
          ? ` (exports: ${exportedNames.map((n) => "`" + n + "`").join(", ")})`
          : ""
      }`,
    );
  }

  return lines.join("\n");
}

// ─── Helper Functions ────────────────────────────────────────────────

interface TreeNode {
  name: string;
  children: TreeNode[];
  fileCount: number;
  isDir: boolean;
  annotation?: string;
}

function buildDirectoryTree(files: ScannedFile[], maxDepth: number): TreeNode {
  const root: TreeNode = { name: ".", children: [], fileCount: 0, isDir: true };

  for (const file of files) {
    const parts = file.path.split("/");
    let current = root;

    for (let i = 0; i < parts.length; i++) {
      const part = parts[i];
      const isFile = i === parts.length - 1;

      if (i >= maxDepth && !isFile) {
        // Don't go deeper than maxDepth for dirs
        current.fileCount++;
        break;
      }

      if (isFile) {
        current.fileCount++;
      } else {
        let child = current.children.find((c) => c.name === part && c.isDir);
        if (!child) {
          child = { name: part, children: [], fileCount: 0, isDir: true };
          current.children.push(child);
        }
        current = child;
      }
    }
  }

  // Annotate directories with file counts
  annotateTree(root);

  return root;
}

function annotateTree(node: TreeNode): number {
  if (!node.isDir) return 1;

  let total = node.fileCount;
  for (const child of node.children) {
    total += annotateTree(child);
  }

  node.fileCount = total;
  if (total > 0) {
    node.annotation = `${total} files`;
  }

  return total;
}

function renderTree(node: TreeNode, prefix: string, isRoot: boolean): string[] {
  const lines: string[] = [];

  // Sort directories first, then by name
  const sorted = [...node.children].sort((a, b) => {
    if (a.isDir && !b.isDir) return -1;
    if (!a.isDir && b.isDir) return 1;
    return a.name.localeCompare(b.name);
  });

  // Only show directories (not individual files at this level)
  const dirs = sorted.filter((c) => c.isDir);

  for (let i = 0; i < dirs.length; i++) {
    const child = dirs[i];
    const isLast = i === dirs.length - 1;
    const connector = isRoot ? "" : isLast ? "└── " : "├── ";
    const childPrefix = isRoot ? "" : isLast ? "    " : "│   ";

    const annotation = child.annotation ? ` (${child.annotation})` : "";
    lines.push(`${prefix}${connector}${child.name}/${annotation}`);

    if (child.children.some((c) => c.isDir)) {
      lines.push(...renderTree(child, prefix + childPrefix, false));
    }
  }

  return lines;
}

function getSymbolIcon(kind: string): string {
  const icons: Record<string, string> = {
    function: "⚡",
    class: "🏛️",
    method: "🔧",
    interface: "📐",
    type: "📝",
    constant: "📌",
    enum: "📊",
    variable: "📦",
    property: "🔑",
    decorator: "🎨",
  };
  return icons[kind] || "•";
}

function cleanSignature(sig: string): string {
  return sig
    .replace(/^export\s+(default\s+)?/, "")
    .replace(/\{.*$/, "")
    .trim()
    .slice(0, 120);
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
